//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWithRef.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://helenaofredrik.se/mcpd/wshttp1/Greet", ConfigurationName="ServiceReference1.IGreet")]
    public interface IGreet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/Say", ReplyAction="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SayResponse")]
        string Say(string something);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/Say", ReplyAction="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SayResponse")]
        System.Threading.Tasks.Task<string> SayAsync(string something);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SaySlowly", ReplyAction="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SaySlowlyResponse")]
        string SaySlowly(string something);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SaySlowly", ReplyAction="http://helenaofredrik.se/mcpd/wshttp1/Greet/IGreet/SaySlowlyResponse")]
        System.Threading.Tasks.Task<string> SaySlowlyAsync(string something);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreetChannel : ClientWithRef.ServiceReference1.IGreet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreetClient : System.ServiceModel.ClientBase<ClientWithRef.ServiceReference1.IGreet>, ClientWithRef.ServiceReference1.IGreet {
        
        public GreetClient() {
        }
        
        public GreetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Say(string something) {
            return base.Channel.Say(something);
        }
        
        public System.Threading.Tasks.Task<string> SayAsync(string something) {
            return base.Channel.SayAsync(something);
        }
        
        public string SaySlowly(string something) {
            return base.Channel.SaySlowly(something);
        }
        
        public System.Threading.Tasks.Task<string> SaySlowlyAsync(string something) {
            return base.Channel.SaySlowlyAsync(something);
        }
    }
}
