//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10.10.2013 08:33:45
namespace WpfClient.NorthwindServiceReference
{
    
    /// <summary>
    /// There are no comments for NorthwindEntities in the schema.
    /// </summary>
    public partial class NorthwindEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NorthwindEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V2)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("NorthwindModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WpfClient.NorthwindServiceReference", typeName.Substring(14)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WpfClient.NorthwindServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("NorthwindModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for Order_Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Order_Detail> Order_Details
        {
            get
            {
                if ((this._Order_Details == null))
                {
                    this._Order_Details = base.CreateQuery<Order_Detail>("Order_Details");
                }
                return this._Order_Details;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Order_Detail> _Order_Details;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<Order>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Order> _Orders;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for Order_Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrder_Details(Order_Detail order_Detail)
        {
            base.AddObject("Order_Details", order_Detail);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    }
    /// <summary>
    /// There are no comments for NorthwindModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Customer_ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Customers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Customer_ID")]
    public partial class Customer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customer_ID">Initial value of Customer_ID.</param>
        /// <param name="company_Name">Initial value of Company_Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(string customer_ID, string company_Name)
        {
            Customer customer = new Customer();
            customer.Customer_ID = customer_ID;
            customer.Company_Name = company_Name;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property Customer_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_ID
        {
            get
            {
                return this._Customer_ID;
            }
            set
            {
                this.OnCustomer_IDChanging(value);
                this._Customer_ID = value;
                this.OnCustomer_IDChanged();
                this.OnPropertyChanged("Customer_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_ID;
        partial void OnCustomer_IDChanging(string value);
        partial void OnCustomer_IDChanged();
        /// <summary>
        /// There are no comments for Property Company_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Company_Name
        {
            get
            {
                return this._Company_Name;
            }
            set
            {
                this.OnCompany_NameChanging(value);
                this._Company_Name = value;
                this.OnCompany_NameChanged();
                this.OnPropertyChanged("Company_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Company_Name;
        partial void OnCompany_NameChanging(string value);
        partial void OnCompany_NameChanged();
        /// <summary>
        /// There are no comments for Property Contact_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Contact_Name
        {
            get
            {
                return this._Contact_Name;
            }
            set
            {
                this.OnContact_NameChanging(value);
                this._Contact_Name = value;
                this.OnContact_NameChanged();
                this.OnPropertyChanged("Contact_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Contact_Name;
        partial void OnContact_NameChanging(string value);
        partial void OnContact_NameChanged();
        /// <summary>
        /// There are no comments for Property Contact_Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Contact_Title
        {
            get
            {
                return this._Contact_Title;
            }
            set
            {
                this.OnContact_TitleChanging(value);
                this._Contact_Title = value;
                this.OnContact_TitleChanged();
                this.OnPropertyChanged("Contact_Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Contact_Title;
        partial void OnContact_TitleChanging(string value);
        partial void OnContact_TitleChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Region in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this.OnRegionChanging(value);
                this._Region = value;
                this.OnRegionChanged();
                this.OnPropertyChanged("Region");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Region;
        partial void OnRegionChanging(string value);
        partial void OnRegionChanged();
        /// <summary>
        /// There are no comments for Property Postal_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Postal_Code
        {
            get
            {
                return this._Postal_Code;
            }
            set
            {
                this.OnPostal_CodeChanging(value);
                this._Postal_Code = value;
                this.OnPostal_CodeChanged();
                this.OnPropertyChanged("Postal_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Postal_Code;
        partial void OnPostal_CodeChanging(string value);
        partial void OnPostal_CodeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Fax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnFaxChanging(value);
                this._Fax = value;
                this.OnFaxChanged();
                this.OnPropertyChanged("Fax");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Fax;
        partial void OnFaxChanging(string value);
        partial void OnFaxChanged();
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Order> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                this._Orders = value;
                this.OnPropertyChanged("Orders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Order> _Orders = new global::System.Data.Services.Client.DataServiceCollection<Order>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NorthwindModel.Order_Detail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Order_ID
    /// Product_ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Order_Details")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Order_ID", "Product_ID")]
    public partial class Order_Detail : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order_Detail object.
        /// </summary>
        /// <param name="order_ID">Initial value of Order_ID.</param>
        /// <param name="product_ID">Initial value of Product_ID.</param>
        /// <param name="unit_Price">Initial value of Unit_Price.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="discount">Initial value of Discount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Order_Detail CreateOrder_Detail(int order_ID, int product_ID, decimal unit_Price, short quantity, float discount)
        {
            Order_Detail order_Detail = new Order_Detail();
            order_Detail.Order_ID = order_ID;
            order_Detail.Product_ID = product_ID;
            order_Detail.Unit_Price = unit_Price;
            order_Detail.Quantity = quantity;
            order_Detail.Discount = discount;
            return order_Detail;
        }
        /// <summary>
        /// There are no comments for Property Order_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Order_ID
        {
            get
            {
                return this._Order_ID;
            }
            set
            {
                this.OnOrder_IDChanging(value);
                this._Order_ID = value;
                this.OnOrder_IDChanged();
                this.OnPropertyChanged("Order_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Order_ID;
        partial void OnOrder_IDChanging(int value);
        partial void OnOrder_IDChanged();
        /// <summary>
        /// There are no comments for Property Product_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Product_ID
        {
            get
            {
                return this._Product_ID;
            }
            set
            {
                this.OnProduct_IDChanging(value);
                this._Product_ID = value;
                this.OnProduct_IDChanged();
                this.OnPropertyChanged("Product_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Product_ID;
        partial void OnProduct_IDChanging(int value);
        partial void OnProduct_IDChanged();
        /// <summary>
        /// There are no comments for Property Unit_Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Unit_Price
        {
            get
            {
                return this._Unit_Price;
            }
            set
            {
                this.OnUnit_PriceChanging(value);
                this._Unit_Price = value;
                this.OnUnit_PriceChanged();
                this.OnPropertyChanged("Unit_Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Unit_Price;
        partial void OnUnit_PriceChanging(decimal value);
        partial void OnUnit_PriceChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _Quantity;
        partial void OnQuantityChanging(short value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Discount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float Discount
        {
            get
            {
                return this._Discount;
            }
            set
            {
                this.OnDiscountChanging(value);
                this._Discount = value;
                this.OnDiscountChanged();
                this.OnPropertyChanged("Discount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _Discount;
        partial void OnDiscountChanging(float value);
        partial void OnDiscountChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Product _Product;
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Order Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Order _Order;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NorthwindModel.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Order_ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Orders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Order_ID")]
    public partial class Order : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="order_ID">Initial value of Order_ID.</param>
        /// <param name="customer_ID">Initial value of Customer_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Order CreateOrder(int order_ID, string customer_ID)
        {
            Order order = new Order();
            order.Order_ID = order_ID;
            order.Customer_ID = customer_ID;
            return order;
        }
        /// <summary>
        /// There are no comments for Property Order_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Order_ID
        {
            get
            {
                return this._Order_ID;
            }
            set
            {
                this.OnOrder_IDChanging(value);
                this._Order_ID = value;
                this.OnOrder_IDChanged();
                this.OnPropertyChanged("Order_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Order_ID;
        partial void OnOrder_IDChanging(int value);
        partial void OnOrder_IDChanged();
        /// <summary>
        /// There are no comments for Property Customer_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_ID
        {
            get
            {
                return this._Customer_ID;
            }
            set
            {
                this.OnCustomer_IDChanging(value);
                this._Customer_ID = value;
                this.OnCustomer_IDChanged();
                this.OnPropertyChanged("Customer_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_ID;
        partial void OnCustomer_IDChanging(string value);
        partial void OnCustomer_IDChanged();
        /// <summary>
        /// There are no comments for Property Employee_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Employee_ID
        {
            get
            {
                return this._Employee_ID;
            }
            set
            {
                this.OnEmployee_IDChanging(value);
                this._Employee_ID = value;
                this.OnEmployee_IDChanged();
                this.OnPropertyChanged("Employee_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Employee_ID;
        partial void OnEmployee_IDChanging(global::System.Nullable<int> value);
        partial void OnEmployee_IDChanged();
        /// <summary>
        /// There are no comments for Property Ship_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_Name
        {
            get
            {
                return this._Ship_Name;
            }
            set
            {
                this.OnShip_NameChanging(value);
                this._Ship_Name = value;
                this.OnShip_NameChanged();
                this.OnPropertyChanged("Ship_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_Name;
        partial void OnShip_NameChanging(string value);
        partial void OnShip_NameChanged();
        /// <summary>
        /// There are no comments for Property Ship_Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_Address
        {
            get
            {
                return this._Ship_Address;
            }
            set
            {
                this.OnShip_AddressChanging(value);
                this._Ship_Address = value;
                this.OnShip_AddressChanged();
                this.OnPropertyChanged("Ship_Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_Address;
        partial void OnShip_AddressChanging(string value);
        partial void OnShip_AddressChanged();
        /// <summary>
        /// There are no comments for Property Ship_City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_City
        {
            get
            {
                return this._Ship_City;
            }
            set
            {
                this.OnShip_CityChanging(value);
                this._Ship_City = value;
                this.OnShip_CityChanged();
                this.OnPropertyChanged("Ship_City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_City;
        partial void OnShip_CityChanging(string value);
        partial void OnShip_CityChanged();
        /// <summary>
        /// There are no comments for Property Ship_Region in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_Region
        {
            get
            {
                return this._Ship_Region;
            }
            set
            {
                this.OnShip_RegionChanging(value);
                this._Ship_Region = value;
                this.OnShip_RegionChanged();
                this.OnPropertyChanged("Ship_Region");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_Region;
        partial void OnShip_RegionChanging(string value);
        partial void OnShip_RegionChanged();
        /// <summary>
        /// There are no comments for Property Ship_Postal_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_Postal_Code
        {
            get
            {
                return this._Ship_Postal_Code;
            }
            set
            {
                this.OnShip_Postal_CodeChanging(value);
                this._Ship_Postal_Code = value;
                this.OnShip_Postal_CodeChanged();
                this.OnPropertyChanged("Ship_Postal_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_Postal_Code;
        partial void OnShip_Postal_CodeChanging(string value);
        partial void OnShip_Postal_CodeChanged();
        /// <summary>
        /// There are no comments for Property Ship_Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_Country
        {
            get
            {
                return this._Ship_Country;
            }
            set
            {
                this.OnShip_CountryChanging(value);
                this._Ship_Country = value;
                this.OnShip_CountryChanged();
                this.OnPropertyChanged("Ship_Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_Country;
        partial void OnShip_CountryChanging(string value);
        partial void OnShip_CountryChanged();
        /// <summary>
        /// There are no comments for Property Ship_Via in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Ship_Via
        {
            get
            {
                return this._Ship_Via;
            }
            set
            {
                this.OnShip_ViaChanging(value);
                this._Ship_Via = value;
                this.OnShip_ViaChanged();
                this.OnPropertyChanged("Ship_Via");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Ship_Via;
        partial void OnShip_ViaChanging(global::System.Nullable<int> value);
        partial void OnShip_ViaChanged();
        /// <summary>
        /// There are no comments for Property Order_Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Order_Date
        {
            get
            {
                return this._Order_Date;
            }
            set
            {
                this.OnOrder_DateChanging(value);
                this._Order_Date = value;
                this.OnOrder_DateChanged();
                this.OnPropertyChanged("Order_Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Order_Date;
        partial void OnOrder_DateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnOrder_DateChanged();
        /// <summary>
        /// There are no comments for Property Required_Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Required_Date
        {
            get
            {
                return this._Required_Date;
            }
            set
            {
                this.OnRequired_DateChanging(value);
                this._Required_Date = value;
                this.OnRequired_DateChanged();
                this.OnPropertyChanged("Required_Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Required_Date;
        partial void OnRequired_DateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRequired_DateChanged();
        /// <summary>
        /// There are no comments for Property Shipped_Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Shipped_Date
        {
            get
            {
                return this._Shipped_Date;
            }
            set
            {
                this.OnShipped_DateChanging(value);
                this._Shipped_Date = value;
                this.OnShipped_DateChanged();
                this.OnPropertyChanged("Shipped_Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Shipped_Date;
        partial void OnShipped_DateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnShipped_DateChanged();
        /// <summary>
        /// There are no comments for Property Freight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Freight
        {
            get
            {
                return this._Freight;
            }
            set
            {
                this.OnFreightChanging(value);
                this._Freight = value;
                this.OnFreightChanged();
                this.OnPropertyChanged("Freight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Freight;
        partial void OnFreightChanging(global::System.Nullable<decimal> value);
        partial void OnFreightChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for Order_Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Order_Detail> Order_Details
        {
            get
            {
                return this._Order_Details;
            }
            set
            {
                this._Order_Details = value;
                this.OnPropertyChanged("Order_Details");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Order_Detail> _Order_Details = new global::System.Data.Services.Client.DataServiceCollection<Order_Detail>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NorthwindModel.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Product_ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Products")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Product_ID")]
    public partial class Product : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of Product_ID.</param>
        /// <param name="product_Name">Initial value of Product_Name.</param>
        /// <param name="discontinued">Initial value of Discontinued.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int product_ID, string product_Name, bool discontinued)
        {
            Product product = new Product();
            product.Product_ID = product_ID;
            product.Product_Name = product_Name;
            product.Discontinued = discontinued;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Product_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Product_ID
        {
            get
            {
                return this._Product_ID;
            }
            set
            {
                this.OnProduct_IDChanging(value);
                this._Product_ID = value;
                this.OnProduct_IDChanged();
                this.OnPropertyChanged("Product_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Product_ID;
        partial void OnProduct_IDChanging(int value);
        partial void OnProduct_IDChanged();
        /// <summary>
        /// There are no comments for Property Supplier_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Supplier_ID
        {
            get
            {
                return this._Supplier_ID;
            }
            set
            {
                this.OnSupplier_IDChanging(value);
                this._Supplier_ID = value;
                this.OnSupplier_IDChanged();
                this.OnPropertyChanged("Supplier_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Supplier_ID;
        partial void OnSupplier_IDChanging(global::System.Nullable<int> value);
        partial void OnSupplier_IDChanged();
        /// <summary>
        /// There are no comments for Property Category_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Category_ID
        {
            get
            {
                return this._Category_ID;
            }
            set
            {
                this.OnCategory_IDChanging(value);
                this._Category_ID = value;
                this.OnCategory_IDChanged();
                this.OnPropertyChanged("Category_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Category_ID;
        partial void OnCategory_IDChanging(global::System.Nullable<int> value);
        partial void OnCategory_IDChanged();
        /// <summary>
        /// There are no comments for Property Product_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Product_Name
        {
            get
            {
                return this._Product_Name;
            }
            set
            {
                this.OnProduct_NameChanging(value);
                this._Product_Name = value;
                this.OnProduct_NameChanged();
                this.OnPropertyChanged("Product_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Product_Name;
        partial void OnProduct_NameChanging(string value);
        partial void OnProduct_NameChanged();
        /// <summary>
        /// There are no comments for Property English_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string English_Name
        {
            get
            {
                return this._English_Name;
            }
            set
            {
                this.OnEnglish_NameChanging(value);
                this._English_Name = value;
                this.OnEnglish_NameChanged();
                this.OnPropertyChanged("English_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _English_Name;
        partial void OnEnglish_NameChanging(string value);
        partial void OnEnglish_NameChanged();
        /// <summary>
        /// There are no comments for Property Quantity_Per_Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Quantity_Per_Unit
        {
            get
            {
                return this._Quantity_Per_Unit;
            }
            set
            {
                this.OnQuantity_Per_UnitChanging(value);
                this._Quantity_Per_Unit = value;
                this.OnQuantity_Per_UnitChanged();
                this.OnPropertyChanged("Quantity_Per_Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Quantity_Per_Unit;
        partial void OnQuantity_Per_UnitChanging(string value);
        partial void OnQuantity_Per_UnitChanged();
        /// <summary>
        /// There are no comments for Property Unit_Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Unit_Price
        {
            get
            {
                return this._Unit_Price;
            }
            set
            {
                this.OnUnit_PriceChanging(value);
                this._Unit_Price = value;
                this.OnUnit_PriceChanged();
                this.OnPropertyChanged("Unit_Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Unit_Price;
        partial void OnUnit_PriceChanging(global::System.Nullable<decimal> value);
        partial void OnUnit_PriceChanged();
        /// <summary>
        /// There are no comments for Property Units_In_Stock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> Units_In_Stock
        {
            get
            {
                return this._Units_In_Stock;
            }
            set
            {
                this.OnUnits_In_StockChanging(value);
                this._Units_In_Stock = value;
                this.OnUnits_In_StockChanged();
                this.OnPropertyChanged("Units_In_Stock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _Units_In_Stock;
        partial void OnUnits_In_StockChanging(global::System.Nullable<short> value);
        partial void OnUnits_In_StockChanged();
        /// <summary>
        /// There are no comments for Property Units_On_Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> Units_On_Order
        {
            get
            {
                return this._Units_On_Order;
            }
            set
            {
                this.OnUnits_On_OrderChanging(value);
                this._Units_On_Order = value;
                this.OnUnits_On_OrderChanged();
                this.OnPropertyChanged("Units_On_Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _Units_On_Order;
        partial void OnUnits_On_OrderChanging(global::System.Nullable<short> value);
        partial void OnUnits_On_OrderChanged();
        /// <summary>
        /// There are no comments for Property Reorder_Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> Reorder_Level
        {
            get
            {
                return this._Reorder_Level;
            }
            set
            {
                this.OnReorder_LevelChanging(value);
                this._Reorder_Level = value;
                this.OnReorder_LevelChanged();
                this.OnPropertyChanged("Reorder_Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _Reorder_Level;
        partial void OnReorder_LevelChanging(global::System.Nullable<short> value);
        partial void OnReorder_LevelChanged();
        /// <summary>
        /// There are no comments for Property Discontinued in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Discontinued
        {
            get
            {
                return this._Discontinued;
            }
            set
            {
                this.OnDiscontinuedChanging(value);
                this._Discontinued = value;
                this.OnDiscontinuedChanged();
                this.OnPropertyChanged("Discontinued");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Discontinued;
        partial void OnDiscontinuedChanging(bool value);
        partial void OnDiscontinuedChanged();
        /// <summary>
        /// There are no comments for Order_Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Order_Detail> Order_Details
        {
            get
            {
                return this._Order_Details;
            }
            set
            {
                this._Order_Details = value;
                this.OnPropertyChanged("Order_Details");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Order_Detail> _Order_Details = new global::System.Data.Services.Client.DataServiceCollection<Order_Detail>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
