//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HierarchiesWithEF4
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HierarchiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HierarchiesContainer object using the connection string found in the 'HierarchiesContainer' section of the application configuration file.
        /// </summary>
        public HierarchiesContainer() : base("name=HierarchiesContainer", "HierarchiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HierarchiesContainer object.
        /// </summary>
        public HierarchiesContainer(string connectionString) : base(connectionString, "HierarchiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HierarchiesContainer object.
        /// </summary>
        public HierarchiesContainer(EntityConnection connection) : base(connection, "HierarchiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TphAnimal> TphAnimalSet
        {
            get
            {
                if ((_TphAnimalSet == null))
                {
                    _TphAnimalSet = base.CreateObjectSet<TphAnimal>("TphAnimalSet");
                }
                return _TphAnimalSet;
            }
        }
        private ObjectSet<TphAnimal> _TphAnimalSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TptAnimal> TptAnimals
        {
            get
            {
                if ((_TptAnimals == null))
                {
                    _TptAnimals = base.CreateObjectSet<TptAnimal>("TptAnimals");
                }
                return _TptAnimals;
            }
        }
        private ObjectSet<TptAnimal> _TptAnimals;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TphAnimalSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTphAnimalSet(TphAnimal tphAnimal)
        {
            base.AddObject("TphAnimalSet", tphAnimal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TptAnimals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTptAnimals(TptAnimal tptAnimal)
        {
            base.AddObject("TptAnimals", tptAnimal);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TphAnimal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(TphMammal))]
    [KnownTypeAttribute(typeof(TphInsect))]
    public abstract partial class TphAnimal : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TphInsect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TphInsect : TphAnimal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TphInsect object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="antennaCount">Initial value of the AntennaCount property.</param>
        public static TphInsect CreateTphInsect(global::System.Int32 id, global::System.String name, global::System.Int32 antennaCount)
        {
            TphInsect tphInsect = new TphInsect();
            tphInsect.Id = id;
            tphInsect.Name = name;
            tphInsect.AntennaCount = antennaCount;
            return tphInsect;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AntennaCount
        {
            get
            {
                return _AntennaCount;
            }
            set
            {
                OnAntennaCountChanging(value);
                ReportPropertyChanging("AntennaCount");
                _AntennaCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AntennaCount");
                OnAntennaCountChanged();
            }
        }
        private global::System.Int32 _AntennaCount;
        partial void OnAntennaCountChanging(global::System.Int32 value);
        partial void OnAntennaCountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TphMammal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TphMammal : TphAnimal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TphMammal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="daysPregnancy">Initial value of the DaysPregnancy property.</param>
        public static TphMammal CreateTphMammal(global::System.Int32 id, global::System.String name, global::System.Int32 daysPregnancy)
        {
            TphMammal tphMammal = new TphMammal();
            tphMammal.Id = id;
            tphMammal.Name = name;
            tphMammal.DaysPregnancy = daysPregnancy;
            return tphMammal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DaysPregnancy
        {
            get
            {
                return _DaysPregnancy;
            }
            set
            {
                OnDaysPregnancyChanging(value);
                ReportPropertyChanging("DaysPregnancy");
                _DaysPregnancy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DaysPregnancy");
                OnDaysPregnancyChanged();
            }
        }
        private global::System.Int32 _DaysPregnancy;
        partial void OnDaysPregnancyChanging(global::System.Int32 value);
        partial void OnDaysPregnancyChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TptAnimal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(TptMammal))]
    [KnownTypeAttribute(typeof(TptInsect))]
    public abstract partial class TptAnimal : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TptInsect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TptInsect : TptAnimal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TptInsect object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="antennaCount">Initial value of the AntennaCount property.</param>
        public static TptInsect CreateTptInsect(global::System.Int32 id, global::System.String name, global::System.Int32 antennaCount)
        {
            TptInsect tptInsect = new TptInsect();
            tptInsect.Id = id;
            tptInsect.Name = name;
            tptInsect.AntennaCount = antennaCount;
            return tptInsect;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AntennaCount
        {
            get
            {
                return _AntennaCount;
            }
            set
            {
                OnAntennaCountChanging(value);
                ReportPropertyChanging("AntennaCount");
                _AntennaCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AntennaCount");
                OnAntennaCountChanged();
            }
        }
        private global::System.Int32 _AntennaCount;
        partial void OnAntennaCountChanging(global::System.Int32 value);
        partial void OnAntennaCountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hierarchies", Name="TptMammal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TptMammal : TptAnimal
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TptMammal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="daysPregnancy">Initial value of the DaysPregnancy property.</param>
        public static TptMammal CreateTptMammal(global::System.Int32 id, global::System.String name, global::System.Int32 daysPregnancy)
        {
            TptMammal tptMammal = new TptMammal();
            tptMammal.Id = id;
            tptMammal.Name = name;
            tptMammal.DaysPregnancy = daysPregnancy;
            return tptMammal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DaysPregnancy
        {
            get
            {
                return _DaysPregnancy;
            }
            set
            {
                OnDaysPregnancyChanging(value);
                ReportPropertyChanging("DaysPregnancy");
                _DaysPregnancy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DaysPregnancy");
                OnDaysPregnancyChanged();
            }
        }
        private global::System.Int32 _DaysPregnancy;
        partial void OnDaysPregnancyChanging(global::System.Int32 value);
        partial void OnDaysPregnancyChanged();

        #endregion

    
    }

    #endregion

    
}
