//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalEntities
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Animal
    {
        public Animal()
        {
            this.Habitat = new HashSet<Habitat>();
        }
    
        public int Id { get; set; }
        public string RaceName { get; set; }
    
        public virtual ICollection<Habitat> Habitat { get; set; }
    }
}
